[package]
name = "nodo"
version = "0.1.0"
authors = ["Jeffas <dev@jeffas.io>"]
edition = "2018"

[dependencies]
pulldown-cmark = "0.6"
structopt = "0.3"
log = "0.4"
stderrlog = "0.4"
dirs = "2.0"
walkdir = "2"
regex = "1"
lazy_static = "1.4.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
